# config.yaml
# This file contains the configuration for the olsync application.

overleaf:
  # The base URL for the Overleaf API.
  # This should typically be "https://www.overleaf.com".
  baseUrl: "https://www.overleaf.com"
  # baseUrl: "http://localhost:8880" # local overleaf server

  # The session cookies required for authentication.
  # You can get these from your browser's developer tools after logging in.
  cookies:
    - name: "overleaf_session2"
      value: ""
    # for local overleaf server
    # - name: "overleaf.sid"
    #   value: ""

backup:
  path: "./Backup"            # 备份文件夹，支持相对路径
  schedule: "0 * */6 * * *"     # Cron 表达式，每 6 小时备份一次
  keep_last: 5                # 保留最近 5 个备份，自动清理旧文件

projects:
  include:                        # 通过项目名列表来确定需要备份哪些项目
    - "quick-LaTeX"